<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class SiteConfiguration extends Model
{
    protected $fillable = ['STRIPE_KEY', 'STRIPE_SECRET', 'STRIPE_CLIENT_ID', 'STRIPE_WEBHOOK_SECRET', 'STRIPE_PAYOUT_DELAY', 'EXPESS_PROD_ID', 'MONTHLY_PLAN', 'YEARLY_PLAN', 'STRIPE_CONNECT_LINK', 'SHOP_URL', 'DISCORD_AUTH_REDIRECT', 'BOT_CONNECTION', 'DISCORD_CLIENT_ID', 'DISCORD_SECRET', 'DISCORD_BOT_LINK'];
}
