@extends('layouts.site')

@section('title', 'Terms of Service')
@section('metadata')
<meta name="description" content="The terms of service and use.">
<meta name="keywords" content="TOS,Terms of Service">
<meta name="author" content="BeastlyBot">
<meta http-equiv="Cache-Control" content="no-cache, no-store, must-revalidate" />
<meta http-equiv="Pragma" content="no-cache" />
<meta http-equiv="Expires" content="0" />
<meta name="robots" content="noindex" />
@endsection
@section('content')
<!--page-title starts-->
<div class="page-title-area bg-grey-2">
			<div class="container">
				<div class="row height-300 pt-70 align-items-center">
					<div class="col-lg-12">
						<div class="page-title section-title text-center">
							<h1><span class="text-white">TOS</span></h1>
							<div class="site-breadcrumb">
								<nav aria-label="breadcrumb">
								  <ol class="breadcrumb">
									<li class="breadcrumb-item"><a href="/">Home</a></li>
									<li class="breadcrumb-item active" aria-current="page">TOS</li>
								  </ol>
								</nav>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<!--page-title ends-->

		<!--faq-area start-->
		<div class="faw-area pt-95 pt-sm-77 pb-75">
			<div class="container">
                <h2 class="title">BeastlyBot Terms of Service</h2>
                <h3 id="thegist">The gist:</h3>
                <p>We (the folks at BeastlyBot) run a membership bot platform for Discord called <a href="https://BeastlyBot.com">BeastlyBot</a> and would <strong>love</strong> for you to use it. BeastlyBot service is free to try in demo mode, and we offer <a href="https://BeastlyBot.com/#pricing">paid plans</a> for real-world usage with live payment provider integrations and other features. Our service is designed to give you as much control and ownership over what goes with your membership bot for Discord as possible and encourage you to express yourself freely. However, be responsible in what you publish and sell. In particular, make sure that none of the prohibited items (like spam, viruses, or serious threats of violence) appear in your membership bot. If you find a bot running on BeastlyBot platform that you believe violates these Terms of Service, please <!--<a href="#">contact us</a>-->contact us.</p>
                <p>This document is an adaptation of <a href="https://en.wordpress.com/tos/">WordPress Terms of Service</a>. The original work is available under a <a href="https://creativecommons.org/licenses/by-sa/4.0/">Creative Commons Sharealike</a> license, which means you're more than welcome to re-purpose it for your own use. </p>
                <h3 id="termsofservice">Terms of Service:</h3>
                <p>The following terms and conditions ("Terms") govern all use of the BeastlyBot website, <!--@BeastlyBot-->in Discord and all content, services, and products available at or through the website and the bot (taken together, our "Services"). Our Services are offered subject to your acceptance without modification of all of the terms and conditions contained herein and all other operating rules, policies (including, without limitation, <a href="https://BeastlyBot.com/privacy">BeastlyBot's Privacy Policy</a>) and procedures that may be published from time to time by BeastlyBot (collectively, the "Agreement"). You agree that we may automatically upgrade our Services, and these Terms will apply to any upgrades. </p>
                <p>We refer to BeastlyBot LLC as “BeastlyBot” or “we” throughout this agreement.</p>
                <p>Please read this Agreement carefully before accessing or using our Services. By accessing or using any part of our Services, you agree to become bound by the Terms of this Agreement. If you do not agree to all the Terms of this Agreement, then you may not access or use any of our Services. If these Terms are considered an offer by BeastlyBot, acceptance is expressly limited to these Terms. </p>
                <p>Our Services are not directed to children. Access to and use of our Services is only for those over the age of 13 (or 16 in the European Union). If you are younger than this, you may not register for or use our Services. Any person who registers as a user or provides their personal information to our Services represents that they are 13 years of age or older (16 years or older in the European Union).</p>
                <p>Use of our Services requires an BeastlyBot account and a <a href="https://Discord.com">Discord</a> account. BeastlyBot account is based on Discord account and created automatically when you log in using Discord Login Widget on BeastlyBot website. You will be solely responsible and liable for any activity that occurs under your BeastlyBot account and your membership bot. You are responsible for keeping your BeastlyBot account secure, which means you must keep your Discord account secure as well.  </p>
                <h4 id="1BeastlyBot">1. BeastlyBot.</h4>
                <ul>
                <li><p><strong>Description.</strong> BeastlyBot is a membership bot platform for paid Discord channels and groups. It allows everyone create a membership bot for Discord and automate paid Discord channels and groups management.</p></li>
                <li><p><strong>Your BeastlyBot Account and Membership Bot.</strong> If you create a membership bot on BeastlyBot, you are responsible for maintaining the security of your account and bot, and you are fully responsible for all activities that occur under the account and any other actions taken in connection with the bot. You must immediately notify BeastlyBot of any unauthorized uses of your bot, your BeastlyBot or Discord account, or any other breaches of security. BeastlyBot will not be liable for any acts or omissions by you, including any damages of any kind incurred as a result of such acts or omissions. If you lose access to your Discord account, you may not be able to access your BeastlyBot account.</p></li>
                <li><p><strong>Responsibility of Contributors.</strong> If you operate a membership bot, post material to BeastlyBot, post links on BeastlyBot, or otherwise make (or allow any third party to make) material available (any such material, "Content"), you are entirely responsible for the content of, and any harm resulting from, that Content or your conduct. That is the case regardless of what form the Content takes, which includes, but is not limited to text, photo, video, audio, or code. By using BeastlyBot, you represent and warrant that your Content and conduct do not violate an applicable laws. By submitting Content to BeastlyBot for inclusion in your membership bot, you grant BeastlyBot a world-wide, royalty-free, and non-exclusive license to reproduce, modify, adapt and publish the Content solely for the purpose of displaying, distributing, and promoting your membership bot. If you delete Content, BeastlyBot will use reasonable efforts to remove it from BeastlyBot, but you acknowledge that caching or references to the Content may not be made immediately unavailable. Without limiting any of those representations or warranties, BeastlyBot has the right (though not the obligation) to, in BeastlyBot’s sole discretion, (i) shutdown your membership bot due to prolonged inactivity, (ii) refuse or remove any content that, in BeastlyBot’s reasonable opinion, violates any BeastlyBot policy or is in any way harmful or objectionable, or (iii) terminate or deny access to and use of BeastlyBot to any individual or entity for any reason. BeastlyBot will have no obligation to provide a refund of any amounts previously paid.</p></li>
                <li><p><strong>License.</strong> You agree that we may compile aggregated/anonymized statistics of your membership bot for our internal use to optimize BeastlyBot’s performance.</p></li>
                <li><p><strong>Features.</strong> BeastlyBot includes various features, and you can visit BeastlyBot.com to learn more about them.</p></li>
                <li><p><strong>Taxes.</strong> You are responsible for all taxes and fees associated with your ecommerce activities. You must collect, report, and/or pay the correct amounts to the appropriate authorities, if applicable, and if needed, inform your customers about any taxes they may be required to pay and issue appropriate invoices. Tax laws differ from jurisdiction to jurisdiction and may be subject to different interpretations by different authorities. We recommend you consult an appropriate tax professional for your specific tax situation.</p></li>
                <li><p><strong>Prohibited Uses.</strong> When using BeastlyBot, you agree not to:</p>
                <ul>
                <li>Publish material or engage in activity that is illegal under applicable law.</li>
                <li>Overburden BeastlyBot's systems, as determined by us in our sole discretion.</li>
                <li>Disclose the sensitive personal information of others.</li>
                <li>Send spam or bulk unsolicited messages.</li>
                <li>Interfere with, disrupt, or attack any service or network.</li>
                <li>Distribute material that is or enables malware, spyware, adware, or other malicious code.</li></ul></li>
                <li><p><strong>Cancellation.</strong> If you cancel your subscription to BeastlyBot, we will queue your membership bot for deletion.</p></li>
                <li><p><strong>Third Party Services.</strong> You may choose to set up and/or use third party services, such <a href="https://stripe.com/">Stripe</a> to collect payments. If you do so, be aware that some of your — and your customers’ — data may be passed to the respective third party, and the respective third party’s terms of service, privacy policy, and other policies may apply. We are not involved in these relationships. </p></li>
                <li><p><strong>Your Responsibilities.</strong> You are solely responsible for all of your ecommerce activities, including your membership bot, your subscription plans and benefits, its operation, all applicable taxes and fees, compliance with the Payment Card Industry Data Security Standard (PCI DSS), and compliance with any applicable laws. Among other things, this means that:</p>
                <ul>
                <li>You should use your best judgment when setting up your store, operating your store, processing payments, and selling items. For example, you may want to publish payment and return policies.</li>
                <li>We are not involved in your relationships or transactions with any customer or potential customer.</li>
                <li>You are responsible for resolving all support questions, comments, and complaints, including refunds, chargebacks, or pricing questions. You should provide contact information so that customers may contact you with questions or complaints.</li>
                <li>You are responsible for fulfilling all promises, representations, or warranties you make to them in connection with a sale.</li></ul></li>
                </ul>
                <h4 id="2responsibilityofvisitors">2. Responsibility of Visitors.</h4>
                <p>BeastlyBot has not reviewed, and cannot review, all of the material, including computer software, posted to our Services, and cannot therefore be responsible for that material's content, use or effects. By operating our Services, BeastlyBot does not represent or imply that it endorses the material there posted, or that it believes such material to be accurate, useful, or non-harmful. You are responsible for taking precautions as necessary to protect yourself and your computer systems from viruses, worms, Trojan horses, and other harmful or destructive content. Our Services may contain content that is offensive, indecent, or otherwise objectionable, as well as content containing technical inaccuracies, typographical mistakes, and other errors. Our Services may also contain material that violates the privacy or publicity rights, or infringes the intellectual property and other proprietary rights, of third parties, or the downloading, copying or use of which is subject to additional terms and conditions, stated or unstated. BeastlyBot disclaims any responsibility for any harm resulting from the use by visitors of our Services, or from any downloading by those visitors of content there posted.</p>
                <h3 id="3feespaymentandrenewal">3. Fees, Payment, and Renewal.</h3>
                <h4>For server Subscribers</h4>
                <ul>
                <li><strong>Fees.</strong> By using our Paid Services, you agree to pay the specified fees, which we'll bill or charge you for in regular intervals (such as monthly, annually, or biennially), on a pre-pay basis until you cancel, which you can do at any time on the account subscriptions page.</li>
                <li><strong>Payment.</strong> If your payment fails or Paid Services are otherwise not paid for on time, we may immediately cancel or revoke your access to the Paid Services. If you contact your bank or credit card company to decline or reverse the charge of fees for Paid Services, we may revoke your access to our Services in general.</li>
                <!--<li><strong>Refunds.</strong> You may request a refund at any time from the subscriptions page, this will notify the server owner. However, a refund is at the sole discretion of the server owner unless the Shop otherwise specified as "No Questions Asked" at the time of request and are within the refund time period specified. Our payment processor will issue the refund request right away to the bank, but funds may take 7-10 business days to be seen. BeastlyBot does not have any control over subscriptions and are only a mediary between the server owner and your payment, we can only help with a request for a refund. You will not be able to resubscribe to the same product for 30 days. Fees are non-refundable.</li>-->
                <li><strong>Refunds.</strong>You can request a refund anytime during the first period of your subscription. There are a few factors in-which decide what happens.
                  Every subscription refund is up to the discretion of the server owner, however if the shop says "No Questions Asked" and you are within their refund policy time-frame listed when your subscription will refund instantly.
                  If the server owner fails to refund the server owner can be punished. You can contact us at team@beasty.app.
                  However, if the refund policy is "by server owner discretion with reason" you can request anytime during your time of purchase-subscription refund term with a reason. Your best luck is to request during their refund policy timeline.
                  If the server has no refund policy (or you are outside the refund policy), you can request a refund at any time during the subscriptions first billing term with a reason.
                  The Beastly Bot cannot issue a refund for the server owner. Please trust who you are paying!<br>
                  Fees may be non-refundable. You cannot cancel a refund request. After issued, you will be removed immediately from the role. Refunds can take up to 10 days to make it back to your bank.
                </li>
                <li><strong>Fee Changes.</strong> We may change our fees at any time. When applicable, we may give you advance notice of the fee changes. If you don't agree with the fee changes, you can cancel your Paid Service.</li>
                <li><strong>Unsubscribing.</strong> You may unsubscribe at any time in the account subscriptions page. This will terminate your subscription at the end of your period. Once unsubscribed you cannot request a refund and you cannot resubscribe for 30 days.</li>
                <li><strong>Disputes/Chargebacks.</strong> Disputes and chargebacks are taken very seriously. If lost you will lose all access to your subscriptions without a refund. We have chargeback and dispute protection and will send all evidence to your bank. This can take as long as 2 months. Just contact your shop owner or the Beastly Bot team first please, we're friendly.</li>                
                </ul>
                <h4>For server Owners</h4>
                <ul>
                <li><strong>Transactions & Withdrawal.</strong> We are an intermediary between our Stripe Express users and the customer (you), we hold all funds from every transaction for the specified withdrawal period in escrow before they are released to our user's Stripe Express account.</li>
                <li><strong>Fees.</strong> Some of our Services are offered for free — for example, you can try BeastlyBot in demo mode. To accept live payments you'll need to subscribe to our Paid Services. By using our Paid Services, you agree to pay the specified fees, which we'll bill or charge you for in regular intervals (such as monthly, annually, or biennially), on a pre-pay basis until you cancel, which you can do at any time on the account settings page. Each transaction is subject to a 5%-15% fee (including Stripe fees) depending on the shops active subscribers, as per this structure [15%: under 10 subscribers, 10%: under 100 subscribers, 5%: 1000 or more subscribers]. Store disputes can increase store-wide transaction fee in increments of 5%.</li>
                <li><strong>Payment.</strong> If your payment fails or Paid Services are otherwise not paid for on time, we may immediately cancel or revoke your access to the Paid Services. If you contact your bank or credit card company to decline or reverse the charge of fees for Paid Services, we may revoke your access to our Services in general. Payments made to your Beastly Bot shop are held for the withdrawal period before automatically being released to your Stripe Express. We hold all payments for up to 1 day (usually 1 hour) before payout to ensure less risk on disputes and chargebacks.</li>
                <li><strong>Automatic Renewal.</strong> To ensure uninterrupted service, our Paid Services are automatically renewed. This means that unless you cancel a Paid Service before the end of the applicable subscription period, it will automatically renew, and you authorize us to invoice you or use any payment mechanism we have on record for you to collect the then-applicable subscription fee (as well as any taxes). Your Paid Services are renewed for the same interval of time. For example, if you purchase a BeastlyBot annual plan, you will be charged each year.</li>
                <li><strong>Refunds.</strong> While you may cancel a Paid Service at any time, refunds are issued in our sole discretion. For a subscription to shop Live, you can request a refund within 7 days after first payment. You cannot cancel a refund request. After issued, your shop will turn back to Test and no longer viewable to users. Refunds can take up to 10 days to make it back to your bank. Re-subscribe any time! 
                <br>To refund a users subscription or service from your Shop accept the refund request notification made by the user. If you have selected "No Questions Asked" and do not accept the request we may take action towards your account, such as store deletion or store ban. Fees are non-refundable.
                </li>
                <li><strong>Fee Changes.</strong> We may change our fees at any time. When applicable, we may give you advance notice of the fee changes. If you don't agree with the fee changes, you can cancel your Paid Service.</li>                
                <li><strong>Disputes/Chargebacks.</strong> Disputes to any paid invoice will be transferred back and frozen until resolved. We issue all proof of purchase (IP address, user address, email, service, terms of service) to the bank to hopefully win. If won you will recieve 80% of the funds back. There is a $15 USD dispute charge that will be invoiced (Stripe issues this to us first) and a strike may increase future transaction fees. We may contact us to lower your future fees and resolve the dispute.</li>                
                </ul>
                <h4 id="4contentpostedonotherwebsites">4. Content Posted on Other Websites.</h4>
                <p>We have not reviewed, and cannot review, all of the material, including computer software, made available through the websites and webpages to which BeastlyBot links, and that link to BeastlyBot. BeastlyBot does not have any control over those non-BeastlyBot websites, and is not responsible for their contents or their use. By linking to an external website, BeastlyBot does not represent or imply that it endorses such website. You are responsible for taking precautions as necessary to protect yourself and your computer systems from viruses, worms, Trojan horses, and other harmful or destructive content. BeastlyBot disclaims any responsibility for any harm resulting from your use of non-BeastlyBot websites, webpages and Discord bots.</p>
                <h4 id="5thirdpartyservices">5. Third Party Services.</h4>
                <p>You may enable services, products, software, or applications developed by a third party or yourself (“Third Party Services”) in your membership bot.</p>
                <p>If you use any Third Party Services, you understand that:</p>
                <ul>
                <li>Third Party Services are not vetted, endorsed, or controlled by BeastlyBot.</li>
                <li>Any use of a Third Party Service is at your own risk, and we shall not be responsible or liable to anyone for Third Party Services.</li>
                <li>Your use is solely between you and the respective third party (“Third Party”) and will be governed by the Third Party’s terms and policies. It is your responsibility to review the Third Party’s terms and policies before using a Third Party Service.</li>
                <li>Some Third Party Services may request or require access to your (yours, your visitors’, or customers’) data. If you grant access, your data will handled in accordance with the Third Party’s privacy policy and practices. We do not have control over how a Third Party Service may use your data. You should carefully review Third Party Services’ data collection, retention, and use policies and practices before enabling Third Party Services.</li>
                <li>Third Party Services may not work appropriately with your website, and we may not be able to provide support for issues caused by any Third Party Services.</li>
                <li>If you have questions or concerns about how a Third Party Service operates, or need support, please contact the Third Party directly.</li>
                </ul>
                <p>In rare cases, we may at our discretion, suspend, disable, or remove Third Party Services from your account or membership bot.</p>
                <h4 id="6copyrightinfringement">6. Copyright Infringement.</h4>
                <p>As BeastlyBot asks others to respect its intellectual property rights, it respects the intellectual property rights of others. If you believe that material located on or linked to by BeastlyBot violates your copyright, you are encouraged to notify BeastlyBot. BeastlyBot will respond to all such notices, including as required or appropriate by removing the infringing material or disabling all links to the infringing material. BeastlyBot will terminate a visitor's access to and use of the membership bot if, under appropriate circumstances, the visitor is determined to be a repeat infringer of the copyrights or other intellectual property rights of BeastlyBot or others. In the case of such termination, BeastlyBot will have no obligation to provide a refund of any amounts previously paid to BeastlyBot.</p>
                <h4 id="7intellectualproperty">7. Intellectual Property.</h4>
                <p>This Agreement does not transfer from BeastlyBot to you any BeastlyBot or third party intellectual property, and all right, title, and interest in and to such property will remain (as between the parties) solely with BeastlyBot. BeastlyBot, the BeastlyBot logo, and all other trademarks, service marks, graphics and logos used in connection with BeastlyBot or our Services, are trademarks or registered trademarks of BeastlyBot or BeastlyBot's licensors. Other trademarks, service marks, graphics and logos used in connection with our Services may be the trademarks of other third parties. Your use of our Services grants you no right or license to reproduce or otherwise use any BeastlyBot or third-party trademarks.</p>
                <h4 id="8changes">8. Changes.</h4>
                <p>We are constantly updating our Services, and that means sometimes we have to change the legal terms under which our Services are offered. If we make changes that are material, we will let you know by posting on one of our blogs, Discord channels or by sending you an email or other communication before the changes take effect. The notice will designate a reasonable period of time after which the new terms will take effect. If you disagree with our changes, then you should stop using our Services within the designated notice period. Your continued use of our Services will be subject to the new terms. However, any dispute that arose before the changes shall be governed by the Terms (including the binding individual arbitration clause) that were in place when the dispute arose.</p>
                <h4 id="9termination">9. Termination.</h4>
                <p>BeastlyBot may terminate your access to all or any part of our Services at any time, with or without cause, with or without notice, effective immediately. If you wish to terminate this Agreement or your BeastlyBot account (if you have one), you may simply discontinue using our Services. All provisions of this Agreement which by their nature should survive termination shall survive termination, including, without limitation, ownership provisions, warranty disclaimers, indemnity and limitations of liability.</p>
                <h4 id="10disclaimerofwarranties">10. Disclaimer of Warranties.</h4>
                <p><strong>Our Services are provided "as is." BeastlyBot and its suppliers and licensors hereby disclaim all warranties of any kind, express or implied, including, without limitation, the warranties of merchantability, fitness for a particular purpose and non-infringement. Neither BeastlyBot nor its suppliers and licensors, makes any warranty that our Services will be error free or that access thereto will be continuous or uninterrupted. You understand that you download from, or otherwise obtain content or services through, our Services at your own discretion and risk.</strong></p>
                <h4 id="11jurisdictionandapplicablelaw">11. Jurisdiction and Applicable Law.</h4>
                <p><strong>Except to the extent applicable law, if any, provides otherwise, this Agreement, any access to or use of our Services will be governed by the laws of the state of California, U.S.A., excluding its conflict of law provisions, and the proper venue for any disputes arising out of or relating to any of the same will be the state and federal courts located in San Francisco County, California.</strong></p>
                <h4 id="12arbitrationagreement">12. Arbitration Agreement.</h4>
                <p><strong>Except for claims for injunctive or equitable relief or claims regarding intellectual property rights (which may be brought in any competent court without the posting of a bond), any dispute arising under this Agreement shall be finally settled in accordance with the Comprehensive Arbitration Rules of the Judicial Arbitration and Mediation Service, Inc. ("JAMS") by three arbitrators appointed in accordance with such Rules. The arbitration shall take place in San Francisco, California, in the English language and the arbitral decision may be enforced in any court. The prevailing party in any action or proceeding to enforce this Agreement shall be entitled to costs and attorneys' fees.</strong></p>
                <h4 id="13limitationofliability">13. Limitation of Liability.</h4>
                <p><strong>In no event will BeastlyBot, or its suppliers or licensors, be liable with respect to any subject matter of this Agreement under any contract, negligence, strict liability or other legal or equitable theory for: (i) any special, incidental or consequential damages; (ii) the cost of procurement for substitute products or services; (iii) for interruption of use or loss or corruption of data; or (iv) for any amounts that exceed the fees paid by you to BeastlyBot under this Agreement during the twelve (12) month period prior to the cause of action. BeastlyBot shall have no liability for any failure or delay due to matters beyond their reasonable control. The foregoing shall not apply to the extent prohibited by applicable law.</strong></p>
                <h4 id="14generalrepresentationandwarranty">14. General Representation and Warranty.</h4>
                <p>You represent and warrant that your use of our Services:</p>
                <ul>
                <li>Will be in strict accordance with this Agreement; </li>
                <li>Will comply with all applicable laws and regulations (including without limitation all applicable laws regarding online conduct and acceptable content, the transmission of technical data exported from the United States or the country in which you reside, privacy, and data protection); and</li>
                <li>Will not infringe or misappropriate the intellectual property rights of any third party.</li>
                </ul>
                <h4 id="15useconomicsanctions">15. US Economic Sanctions.</h4>
                <p>You expressly represent and warrant that your use of our Services and or associated services and products is not contrary to applicable U.S. Sanctions. Such use is prohibited, and BeastlyBot reserves the right to terminate accounts or access of those in the event of a breach of this condition.</p>
                <h4 id="16indemnification">16. Indemnification.</h4>
                <p>You agree to indemnify and hold harmless BeastlyBot, its contractors, and its licensors, and their respective directors, officers, employees, and agents from and against any and all claims and expenses, including attorneys' fees, arising out of your use of our Services, including but not limited to your violation of this Agreement.</p>
                <h4 id="17translation">17. Translation.</h4>
                <p>These Terms of Service were originally written in English (US). We may translate these terms into other languages. In the event of a conflict between a translated version of these Terms of Service and the English version, the English version will control.</p>
                <h4 id="18miscellaneous">18. Miscellaneous.</h4>
                <p>This Agreement constitutes the entire agreement between BeastlyBot and you concerning the subject matter hereof, and they may only be modified by a written amendment signed by an authorized executive of BeastlyBot, or by the posting by BeastlyBot of a revised version. </p>
                <p>If any part of this Agreement is held invalid or unenforceable, that part will be construed to reflect the parties' original intent, and the remaining portions will remain in full force and effect. A waiver by either party of any term or condition of this Agreement or any breach thereof, in any one instance, will not waive such term or condition or any subsequent breach thereof. </p>
                <p>You may assign your rights under this Agreement to any party that consents to, and agrees to be bound by, its terms and conditions; BeastlyBot may assign its rights under this Agreement without condition. This Agreement will be binding upon and will inure to the benefit of the parties, their successors and permitted assigns. </p>
                    </div>
</div>


@endsection
